"""AI chat assistant (OpenAI) grounded in the dashboard's own data.

Every request carries a compact context: the latest scan, the market regime, the news
digest, the user's portfolio and, when a coin is selected, its full deterministic
analysis. The assistant explains and discusses; it cannot change a signal. The system
prompt states that the engine's labels, risk checks and data-integrity results are
authoritative (the decision hierarchy: the LLM never overrides them).
"""

from __future__ import annotations

import json
import logging
import time
from collections import deque
from collections.abc import Awaitable, Callable
from typing import Any

import httpx

from app.config import Settings

log = logging.getLogger(__name__)

MAX_MESSAGES = 16
MAX_MESSAGE_CHARS = 4000
MAX_CONTEXT_CHARS = 24000

SYSTEM_PROMPT = """You are the analysis assistant of a crypto spot-trading dashboard.
You help the user think through their next spot trade using the data in CONTEXT.

Rules:
- Use only the numbers in CONTEXT for current prices, levels and signals. If something is
  not in CONTEXT, say you do not have it; never invent prices, news or statistics.
- The dashboard's deterministic engine is authoritative. Its labels (STRONG BUY, BUY,
  WATCH, NO TRADE), risk checks and data-integrity results cannot be overridden by you.
  Never present a NO TRADE or WATCH coin as a buy; you may explain what would need to change.
- Spot only: no leverage, futures or short selling. You cannot place trades.
- Be concrete: entry zone, stop, targets, reward:risk and position size come from the plan.
  Mention the main risks and the invalidation level.
- Signals have no measured track record yet; nothing is guaranteed. Keep answers concise,
  use short lists, and end trade discussions with a one-line risk reminder.
"""


class ChatUnavailable(Exception):
    def __init__(self, message: str, status_code: int = 503) -> None:
        super().__init__(message)
        self.message = message
        self.status_code = status_code


class ChatService:
    def __init__(
        self,
        settings: Settings,
        http: httpx.AsyncClient,
        context: Callable[[str | None], Awaitable[dict[str, Any]]],
        clock: Callable[[], float] = time.monotonic,
    ) -> None:
        self._s = settings
        self._http = http
        self._context = context
        self._clock = clock
        self._recent: deque[float] = deque()

    @property
    def configured(self) -> bool:
        return self._s.openai_configured

    def _rate_limit(self) -> None:
        now = self._clock()
        while self._recent and now - self._recent[0] > 60:
            self._recent.popleft()
        if len(self._recent) >= max(1, self._s.chat_rate_limit_per_minute):
            raise ChatUnavailable("too many chat messages; wait a minute", 429)
        self._recent.append(now)

    @staticmethod
    def _clean(messages: list[dict[str, str]]) -> list[dict[str, str]]:
        cleaned = []
        for m in messages[-MAX_MESSAGES:]:
            role = m.get("role")
            content = str(m.get("content", "")).strip()
            if role in ("user", "assistant") and content:
                cleaned.append({"role": role, "content": content[:MAX_MESSAGE_CHARS]})
        if not cleaned or cleaned[-1]["role"] != "user":
            raise ChatUnavailable("the last message must come from the user", 422)
        return cleaned

    async def reply(self, messages: list[dict[str, str]], symbol: str | None = None) -> dict[str, Any]:
        if not self.configured or self._s.openai_api_key is None:
            raise ChatUnavailable("OPENAI_API_KEY is not set on the server")
        conversation = self._clean(messages)
        self._rate_limit()
        context = await self._context(symbol)
        context_text = json.dumps(context, default=str, separators=(",", ":"))[:MAX_CONTEXT_CHARS]
        payload_messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "system", "content": f"CONTEXT (JSON, generated by the dashboard):\n{context_text}"},
            *conversation,
        ]
        errors: list[str] = []
        for model in self._s.chat_models:
            try:
                text, usage = await self._complete(model, payload_messages)
            except ChatUnavailable as exc:
                if exc.status_code == 404 or "model" in exc.message.lower():
                    errors.append(f"{model}: {exc.message}")
                    continue  # try the fallback model
                raise
            return {"reply": text, "model": model, "usage": usage, "context_symbols": context.get("symbols_in_context", [])}
        raise ChatUnavailable("; ".join(errors) or "no chat model available", 502)

    async def _complete(self, model: str, messages: list[dict[str, str]]) -> tuple[str, dict[str, Any]]:
        assert self._s.openai_api_key is not None
        try:
            response = await self._http.post(
                f"{self._s.openai_base_url.rstrip('/')}/chat/completions",
                json={"model": model, "messages": messages, "max_completion_tokens": self._s.chat_max_output_tokens},
                headers={"Authorization": f"Bearer {self._s.openai_api_key.get_secret_value()}"},
                timeout=httpx.Timeout(90.0, connect=10.0),
            )
        except httpx.HTTPError as exc:
            raise ChatUnavailable(f"OpenAI unreachable: {type(exc).__name__}", 502) from None
        try:
            body = response.json()
        except ValueError:
            body = {}
        if response.status_code >= 400:
            error = body.get("error") if isinstance(body, dict) else None
            message = error.get("message") if isinstance(error, dict) else f"HTTP {response.status_code}"
            code = error.get("code") if isinstance(error, dict) else None
            status = 404 if code == "model_not_found" or response.status_code == 404 else 502
            if response.status_code == 401:
                message = "OpenAI rejected the API key"
            elif response.status_code == 429:
                message = f"OpenAI rate limit or quota: {message}"
            raise ChatUnavailable(str(message)[:300], status)
        try:
            text = body["choices"][0]["message"]["content"] or ""
        except (KeyError, IndexError, TypeError):
            raise ChatUnavailable("unexpected OpenAI response", 502) from None
        if not text.strip():
            text = "(The model returned no text. Try again or shorten the question.)"
        return text.strip(), body.get("usage") or {}
