"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 02:19:53.671777
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index('ix_alerts_ack_created', 'alerts', ['acknowledged', 'created_at'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('listing_source', sa.String(length=32), nullable=True),
    sa.Column('listing_source_id', sa.String(length=64), nullable=True),
    sa.Column('market_source', sa.String(length=32), nullable=True),
    sa.Column('market_symbol', sa.String(length=32), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('is_stablecoin', sa.Boolean(), nullable=False),
    sa.Column('is_wrapped', sa.Boolean(), nullable=False),
    sa.Column('in_universe', sa.Boolean(), nullable=False),
    sa.Column('supported', sa.Boolean(), nullable=False),
    sa.Column('unsupported_reason', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('symbol', name=op.f('uq_assets_symbol'))
    )
    op.create_table('backtest_results',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbols', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('trades', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_results')),
    sa.UniqueConstraint('run_id', name=op.f('uq_backtest_results_run_id'))
    )
    op.create_table('candles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('base_asset', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=True),
    sa.Column('trades', sa.Integer(), nullable=True),
    sa.Column('taker_buy_base', sa.Float(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candles')),
    sa.UniqueConstraint('source', 'symbol', 'timeframe', 'open_time', name='uq_candles_source_symbol_tf_time')
    )
    op.create_index('ix_candles_base_tf_time', 'candles', ['base_asset', 'timeframe', 'open_time'], unique=False)
    op.create_table('market_regimes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=False),
    sa.Column('total_market_cap_usd', sa.Float(), nullable=True),
    sa.Column('btc_dominance_pct', sa.Float(), nullable=True),
    sa.Column('fear_greed_value', sa.Integer(), nullable=True),
    sa.Column('fear_greed_source', sa.String(length=32), nullable=True),
    sa.Column('breadth_pct', sa.Float(), nullable=True),
    sa.Column('volatility_pct', sa.Float(), nullable=True),
    sa.Column('engine_version', sa.String(length=32), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_regimes'))
    )
    op.create_index(op.f('ix_market_regimes_computed_at'), 'market_regimes', ['computed_at'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('universe_rank', sa.Integer(), nullable=False),
    sa.Column('listing_source', sa.String(length=32), nullable=False),
    sa.Column('market_source', sa.String(length=32), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('reference_price_usd', sa.Float(), nullable=True),
    sa.Column('deviation_pct', sa.Float(), nullable=True),
    sa.Column('pct_change_24h', sa.Float(), nullable=True),
    sa.Column('volume_24h_usd', sa.Float(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('data_state', sa.String(length=32), nullable=False),
    sa.Column('data_health_score', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_snapshots'))
    )
    op.create_index(op.f('ix_market_snapshots_batch_id'), 'market_snapshots', ['batch_id'], unique=False)
    op.create_index('ix_market_snapshots_symbol_captured', 'market_snapshots', ['symbol', 'captured_at'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('candle_open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('validated_out_of_sample', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_predictions'))
    )
    op.create_index('ix_model_predictions_symbol_time', 'model_predictions', ['symbol', 'timeframe', 'candle_open_time'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('source_rank', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_news_content_hash')),
    sa.UniqueConstraint('url', name=op.f('uq_news_url'))
    )
    op.create_index(op.f('ix_news_published_at'), 'news', ['published_at'], unique=False)
    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('base_asset', sa.String(length=32), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('best_bid', sa.Float(), nullable=True),
    sa.Column('best_ask', sa.Float(), nullable=True),
    sa.Column('spread_bps', sa.Float(), nullable=True),
    sa.Column('band_pct', sa.Float(), nullable=False),
    sa.Column('bid_depth_quote', sa.Float(), nullable=True),
    sa.Column('ask_depth_quote', sa.Float(), nullable=True),
    sa.Column('imbalance', sa.Float(), nullable=True),
    sa.Column('issues', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orderbook_snapshots'))
    )
    op.create_index('ix_orderbook_snapshots_symbol_captured', 'orderbook_snapshots', ['symbol', 'captured_at'], unique=False)
    op.create_table('portfolio',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio')),
    sa.UniqueConstraint('name', name=op.f('uq_portfolio_name'))
    )
    op.create_table('provider_health',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('circuit_state', sa.String(length=16), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_failures', sa.Integer(), nullable=False),
    sa.Column('rate_limit_hits', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_health'))
    )
    op.create_index('ix_provider_health_provider_time', 'provider_health', ['provider', 'recorded_at'], unique=False)
    op.create_table('sentiment',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(length=16), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentiment'))
    )
    op.create_index('ix_sentiment_scope_symbol_time', 'sentiment', ['scope', 'symbol', 'computed_at'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('signal', sa.String(length=16), nullable=False),
    sa.Column('signal_score', sa.Integer(), nullable=False),
    sa.Column('data_health_score', sa.Integer(), nullable=False),
    sa.Column('data_state', sa.String(length=32), nullable=False),
    sa.Column('entry_low', sa.Float(), nullable=True),
    sa.Column('entry_high', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=16), nullable=True),
    sa.Column('market_regime', sa.String(length=32), nullable=True),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('invalidation', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_backtest', sa.Boolean(), nullable=False),
    sa.Column('ai_confirmed', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('feature_version', sa.String(length=32), nullable=True),
    sa.Column('engine_version', sa.String(length=32), nullable=True),
    sa.Column('input_features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('quant_output', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ai_output', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_index('ix_signals_symbol_created', 'signals', ['symbol', 'created_at'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_table('technical_features',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('candle_open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_features')),
    sa.UniqueConstraint('symbol', 'timeframe', 'candle_open_time', 'feature_version', name='uq_technical_features_key')
    )
    op.create_table('whale_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_uid', sa.String(length=160), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=True),
    sa.Column('from_label', sa.String(length=128), nullable=True),
    sa.Column('to_label', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whale_events')),
    sa.UniqueConstraint('event_uid', name=op.f('uq_whale_events_event_uid'))
    )
    op.create_index('ix_whale_events_symbol_time', 'whale_events', ['symbol', 'occurred_at'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('average_entry', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], name=op.f('fk_portfolio_positions_portfolio_id_portfolio'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_positions')),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='uq_portfolio_positions_symbol')
    )
    op.create_table('risk_settings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('max_risk_per_signal_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('initial_allocation_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('max_allocation_per_opportunity_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('max_dca_allocation_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('max_total_open_allocation_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('fee_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('slippage_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], name=op.f('fk_risk_settings_portfolio_id_portfolio'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_settings')),
    sa.UniqueConstraint('portfolio_id', name=op.f('uq_risk_settings_portfolio_id'))
    )
    op.create_table('signal_outcomes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('mfe_pct', sa.Float(), nullable=True),
    sa.Column('mae_pct', sa.Float(), nullable=True),
    sa.Column('time_to_outcome_seconds', sa.Integer(), nullable=True),
    sa.Column('hit_targets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_signal_outcomes_signal_id_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_outcomes')),
    sa.UniqueConstraint('signal_id', name=op.f('uq_signal_outcomes_signal_id'))
    )
    op.create_table('signal_targets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('level_index', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('allocation_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_signal_targets_signal_id_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_targets')),
    sa.UniqueConstraint('signal_id', 'kind', 'level_index', name='uq_signal_targets_level')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_targets')
    op.drop_table('signal_outcomes')
    op.drop_table('risk_settings')
    op.drop_table('portfolio_positions')
    op.drop_index('ix_whale_events_symbol_time', table_name='whale_events')
    op.drop_table('whale_events')
    op.drop_table('technical_features')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index('ix_signals_symbol_created', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_sentiment_scope_symbol_time', table_name='sentiment')
    op.drop_table('sentiment')
    op.drop_index('ix_provider_health_provider_time', table_name='provider_health')
    op.drop_table('provider_health')
    op.drop_table('portfolio')
    op.drop_index('ix_orderbook_snapshots_symbol_captured', table_name='orderbook_snapshots')
    op.drop_table('orderbook_snapshots')
    op.drop_index(op.f('ix_news_published_at'), table_name='news')
    op.drop_table('news')
    op.drop_index('ix_model_predictions_symbol_time', table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index('ix_market_snapshots_symbol_captured', table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_batch_id'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_market_regimes_computed_at'), table_name='market_regimes')
    op.drop_table('market_regimes')
    op.drop_index('ix_candles_base_tf_time', table_name='candles')
    op.drop_table('candles')
    op.drop_table('backtest_results')
    op.drop_table('assets')
    op.drop_index('ix_alerts_ack_created', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
